development:
  url: 'http://54.199.167.123:8080/vpc_php_serverhost_do.php'
  deployed_host: 'localhost:3000'
  greenpeso_url: 'http://54.199.167.123:8080/request_session.php'
production:
  url: 'http://54.199.167.123:8080/vpc_php_serverhost_do.php'
  deployed_host: '54.199.167.123'
  greenpeso_url: 'http://54.199.167.123:8080/request_session.php'